apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-movie
  name: api-movie
  namespace: movie-isb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-movie
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-movie
    spec:
      serviceAccountName: default
      containers:
        - name: api-movie
          image: registry.digitalocean.com/con-testing/bitbucket.org/isbtotogroup/isbpanel_api_movie:latest
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 512Mi
          env:
            - name: PORT
              value: '5058'
            - name: DB_DRIVER
              value: postgres
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: pg-host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: pg-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: pg-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: pg-dbname
            - name: DB_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: pg-schema
            - name: DB_PORT
              value: '5432'
            - name: DB_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: redis-host
            - name: DB_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stg-db-movie-credentials
                  key: redis-pass
            - name: DB_REDIS_PORT
              value: '6379'
            - name: DB_REDIS_NAME
              value: '7'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-movie
  name: api-movie-service
  namespace: movie-isb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5058
  selector:
    app: api-movie
  type: LoadBalancer